export enum MagicData {
  MinRows = 1,
  MinColumns = 1,
  MaxRows = 20,
  MaxColumns = 20,
  DefaultCellSize = 50,
  DefaultRowsColumnsCount = 5,
  FullCircle = 360,
  SemiCircle = 180,
  EightDirections = 360/8,
  Step45 = 45,
  HtmlDotCellSelector = '.cell',
  StringCell = 'cell',
  StringDiv = 'div',
  StringGameBoard = 'gameboard',
  HtmlCellColumn = 'data-col',
  HtmlCellRow = 'data-row',
}